export const CUNY_CAMPUSES = [
  "Baruch College",
  "Brooklyn College",
  "City College",
  "College of Staten Island",
  "Hunter College",
  "John Jay College",
  "Lehman College",
  "Medgar Evers College",
  "NYC College of Technology",
  "Queens College",
  "York College",
  "BMCC",
  "Guttman CC",
  "Hostos CC",
  "Kingsborough CC",
  "LaGuardia CC",
  "Queensborough CC",
  "CUNY Graduate Center",
  "CUNY Law School",
  "CUNY School of Public Health",
  "Macaulay Honors College",
  "Craig Newmark Graduate School of Journalism"
];